package standard

import "github.com/qwwqe/blic"

var canalEraConnectionSpecs = []blic.ConnectionSpec{
	{LocationNames: []string{"warrington", "stoke-on-trent"}},
	{LocationNames: []string{"stoke-on-trent", "leek"}},
	{LocationNames: []string{"stoke-on-trent", "stone"}},
	{LocationNames: []string{"stone", "burton-upon-trent"}},
	{LocationNames: []string{"stone", "stafford"}},
	{LocationNames: []string{"belper", "derby"}},
	{LocationNames: []string{"nottingham", "derby"}},
	{LocationNames: []string{"derby", "burton-upon-trent"}},
	{LocationNames: []string{"stone", "stafford"}},
	{LocationNames: []string{"stafford", "cannock"}},
	{LocationNames: []string{"farmbrewery1", "cannock"}},
	{LocationNames: []string{"burton-upon-trent", "walsall"}},
	{LocationNames: []string{"burton-upon-trent", "tamworth"}},
	{LocationNames: []string{"cannock", "walsall"}},
	{LocationNames: []string{"cannock", "wolverhampton"}},
	{LocationNames: []string{"wolverhampton", "walsall"}},
	{LocationNames: []string{"wolverhampton", "coalbrookdale"}},
	{LocationNames: []string{"wolverhampton", "dudley"}},
	{LocationNames: []string{"coalbrookdale", "shrewsbury"}},
	{LocationNames: []string{"coalbrookdale", "kidderminster"}},
	{LocationNames: []string{"kidderminster", "dudley"}},
	{LocationNames: []string{"kidderminster", "farmbrewery2", "worcester"}},
	{LocationNames: []string{"worcester", "gloucester"}},
	{LocationNames: []string{"gloucester", "redditch"}},
	{LocationNames: []string{"redditch", "oxford"}},
	{LocationNames: []string{"oxford", "birmingham"}},
	{LocationNames: []string{"birmingham", "worcester"}},
	{LocationNames: []string{"birmingham", "dudley"}},
	{LocationNames: []string{"birmingham", "walsall"}},
	{LocationNames: []string{"birmingham", "tamworth"}},
	{LocationNames: []string{"birmingham", "coventry"}},
	{LocationNames: []string{"tamworth", "nuneaton"}},
}

var railEraConnectionSpecs = []blic.ConnectionSpec{
	{LocationNames: []string{"warrington", "stoke-on-trent"}},
	{LocationNames: []string{"stoke-on-trent", "leek"}},
	{LocationNames: []string{"stoke-on-trent", "stone"}},
	{LocationNames: []string{"stone", "burton-upon-trent"}},
	{LocationNames: []string{"stone", "stafford"}},
	{LocationNames: []string{"belper", "derby"}},
	{LocationNames: []string{"nottingham", "derby"}},
	{LocationNames: []string{"derby", "burton-upon-trent"}},
	{LocationNames: []string{"stone", "stafford"}},
	{LocationNames: []string{"stafford", "cannock"}},
	{LocationNames: []string{"farmbrewery1", "cannock"}},
	{LocationNames: []string{"burton-upon-trent", "tamworth"}},
	{LocationNames: []string{"cannock", "walsall"}},
	{LocationNames: []string{"cannock", "wolverhampton"}},
	{LocationNames: []string{"wolverhampton", "walsall"}},
	{LocationNames: []string{"wolverhampton", "coalbrookdale"}},
	{LocationNames: []string{"wolverhampton", "dudley"}},
	{LocationNames: []string{"coalbrookdale", "shrewsbury"}},
	{LocationNames: []string{"coalbrookdale", "kidderminster"}},
	{LocationNames: []string{"kidderminster", "dudley"}},
	{LocationNames: []string{"kidderminster", "farmbrewery2", "worcester"}},
	{LocationNames: []string{"worcester", "gloucester"}},
	{LocationNames: []string{"gloucester", "redditch"}},
	{LocationNames: []string{"redditch", "oxford"}},
	{LocationNames: []string{"oxford", "birmingham"}},
	{LocationNames: []string{"birmingham", "worcester"}},
	{LocationNames: []string{"birmingham", "dudley"}},
	{LocationNames: []string{"birmingham", "walsall"}},
	{LocationNames: []string{"birmingham", "tamworth"}},
	{LocationNames: []string{"birmingham", "coventry"}},
	{LocationNames: []string{"tamworth", "nuneaton"}},
	{LocationNames: []string{"leek", "belper"}},
	{LocationNames: []string{"stone", "uttoxeter"}},
	{LocationNames: []string{"uttoxeter", "derby"}},
	{LocationNames: []string{"cannock", "burtonupontrent"}},
	{LocationNames: []string{"walsall", "tamworth"}},
	{LocationNames: []string{"nuneaton", "birmingham"}},
	{LocationNames: []string{"nuneaton", "coventry"}},
	{LocationNames: []string{"birmingham", "redditch"}},
}
